begin;
create extension if not exists pgtap with schema extensions;

select plan(16);

select has_table('public', 'workspaces', 'workspaces table exists');
select columns_are(
  'public', 'workspaces', array['id', 'name', 'created_at'],
  'workspaces has exactly the expected columns'
);

-- pgTAP needs the trailing description argument to read the first argument as the schema.
select col_is_pk('public', 'workspaces', 'id', 'id is the primary key');
select col_type_is('public', 'workspaces', 'id', 'uuid', 'id is a uuid');
select col_has_default('public', 'workspaces', 'id', 'id is generated by default');

select col_type_is('public', 'workspaces', 'name', 'text', 'name is text');
select col_not_null('public', 'workspaces', 'name', 'name is required');

select col_type_is(
  'public', 'workspaces', 'created_at', 'timestamp with time zone',
  'created_at is a timestamptz'
);
select col_not_null('public', 'workspaces', 'created_at', 'created_at is required');
select col_has_default('public', 'workspaces', 'created_at', 'created_at is set by default');

select throws_ok(
  $$ insert into public.workspaces (name) values ('') $$,
  '23514',
  null,
  'an empty workspace name is rejected'
);
select throws_ok(
  $$ insert into public.workspaces (name) values (repeat('x', 101)) $$,
  '23514',
  null,
  'a workspace name longer than 100 characters is rejected'
);
select lives_ok(
  $$ insert into public.workspaces (name) values ('Acme Agency') $$,
  'a workspace with a valid name is created'
);

set local role anon;
select is_empty($$ select id from public.workspaces $$, 'anon cannot read workspaces');
reset role;

set local role authenticated;
select is_empty($$ select id from public.workspaces $$, 'authenticated users cannot read workspaces');
reset role;

set local role service_role;
select isnt_empty($$ select id from public.workspaces $$, 'the server role can read workspaces');
reset role;

select * from finish();
rollback;
