begin;
create extension if not exists pgtap with schema extensions;

select plan(19);

create temp table fixture as
select gen_random_uuid() as workspace_a, gen_random_uuid() as workspace_b;

insert into public.workspaces (id, name)
select workspace_a, 'Workspace A' from fixture
union all
select workspace_b, 'Workspace B' from fixture;

select has_table('public', 'runs', 'runs table exists');
select columns_are(
  'public', 'runs', array['id', 'workspace_id', 'claude_session_id', 'created_at'],
  'runs has exactly the expected columns'
);

select col_is_pk('public', 'runs', 'id', 'id is the primary key');
select col_type_is('public', 'runs', 'id', 'uuid', 'id is a uuid');
select col_has_default('public', 'runs', 'id', 'id is generated by default');

select col_type_is('public', 'runs', 'workspace_id', 'uuid', 'workspace_id is a uuid');
select col_not_null('public', 'runs', 'workspace_id', 'workspace_id is required');
select fk_ok(
  'public', 'runs', 'workspace_id', 'public', 'workspaces', 'id',
  'workspace_id references workspaces'
);

select col_type_is('public', 'runs', 'claude_session_id', 'text', 'claude_session_id is text');
select col_not_null('public', 'runs', 'claude_session_id', 'claude_session_id is required');

select col_type_is(
  'public', 'runs', 'created_at', 'timestamp with time zone', 'created_at is a timestamptz'
);
select col_not_null('public', 'runs', 'created_at', 'created_at is required');

select throws_ok(
  $$ insert into public.runs (workspace_id, claude_session_id) select workspace_a, '' from fixture $$,
  '23514',
  null,
  'an empty Claude session id is rejected'
);
select lives_ok(
  $$
    insert into public.runs (workspace_id, claude_session_id)
    select workspace_a, 'session-1' from fixture
  $$,
  'a run is created for a Claude session'
);
select throws_ok(
  $$
    insert into public.runs (workspace_id, claude_session_id)
    select workspace_a, 'session-1' from fixture
  $$,
  '23505',
  null,
  'the same Claude session cannot become two runs in one workspace'
);
select lives_ok(
  $$
    insert into public.runs (workspace_id, claude_session_id)
    select workspace_b, 'session-1' from fixture
  $$,
  'workspaces do not share the session id namespace'
);
select throws_ok(
  $$ delete from public.workspaces where id = (select workspace_a from fixture) $$,
  '23503',
  null,
  'a workspace that still has runs cannot be deleted'
);

set local role anon;
select is_empty($$ select id from public.runs $$, 'anon cannot read runs');
reset role;

set local role authenticated;
select is_empty($$ select id from public.runs $$, 'authenticated users cannot read runs');
reset role;

select * from finish();
rollback;
