begin;
create extension if not exists pgtap with schema extensions;

select plan(31);

create temp table fixture as
select
  gen_random_uuid() as workspace_a,
  gen_random_uuid() as workspace_b,
  gen_random_uuid() as run_in_a,
  gen_random_uuid() as run_in_b;

insert into public.workspaces (id, name)
select workspace_a, 'Workspace A' from fixture
union all
select workspace_b, 'Workspace B' from fixture;

insert into public.runs (id, workspace_id, claude_session_id)
select run_in_a, workspace_a, 'session-a' from fixture
union all
select run_in_b, workspace_b, 'session-b' from fixture;

select has_table('public', 'events', 'events table exists');
select columns_are(
  'public', 'events',
  array['id', 'workspace_id', 'run_id', 'actor_id', 'name', 'props', 'created_at'],
  'events has exactly the columns listed in AGENTS.md section 6'
);

select col_is_pk('public', 'events', 'id', 'id is the primary key');
select col_type_is('public', 'events', 'id', 'uuid', 'id is a uuid');
select col_has_default('public', 'events', 'id', 'id is generated by default');

select col_type_is('public', 'events', 'workspace_id', 'uuid', 'workspace_id is a uuid');
select col_not_null('public', 'events', 'workspace_id', 'workspace_id is required');
select fk_ok(
  'public', 'events', 'workspace_id', 'public', 'workspaces', 'id',
  'workspace_id references workspaces'
);

select col_type_is('public', 'events', 'run_id', 'uuid', 'run_id is a uuid');
select col_is_null('public', 'events', 'run_id', 'run_id is optional for workspace-level events');
select fk_ok(
  'public', 'events', array['workspace_id', 'run_id'],
  'public', 'runs', array['workspace_id', 'id'],
  '(workspace_id, run_id) references a run in the same workspace'
);

select col_type_is('public', 'events', 'actor_id', 'uuid', 'actor_id is a uuid');
select col_is_null('public', 'events', 'actor_id', 'actor_id is optional');

select col_type_is('public', 'events', 'name', 'text', 'name is text');
select col_not_null('public', 'events', 'name', 'name is required');

select col_type_is('public', 'events', 'props', 'jsonb', 'props is jsonb');
select col_not_null('public', 'events', 'props', 'props is required');

select col_type_is(
  'public', 'events', 'created_at', 'timestamp with time zone', 'created_at is a timestamptz'
);
select col_not_null('public', 'events', 'created_at', 'created_at is required');

-- The MVP event list from AGENTS.md section 6; renaming or adding one needs a migration.
select lives_ok(
  $$
    insert into public.events (workspace_id, name)
    select fixture.workspace_a, mvp_event.name
    from fixture
    cross join unnest(array[
      'run_created',
      'participant_joined',
      'comment_posted',
      'steer_message_queued',
      'steer_message_delivered',
      'hold_raised',
      'hold_released',
      'checkpoint_resume',
      'guest_invited',
      'invite_sent',
      'invite_accepted',
      'deposit_started',
      'deposit_completed'
    ]) as mvp_event(name)
  $$,
  'every MVP instrumentation event name is accepted'
);
select throws_ok(
  $$ insert into public.events (workspace_id, name) select workspace_a, 'PreToolUse' from fixture $$,
  '23514',
  null,
  'an event name outside the MVP list is rejected'
);
select is(
  (select props from public.events where name = 'run_created'),
  '{}'::jsonb,
  'props defaults to an empty object'
);
select throws_ok(
  $$
    insert into public.events (workspace_id, name, props)
    select workspace_a, 'run_created', '["not", "an", "object"]'::jsonb from fixture
  $$,
  '23514',
  null,
  'props must be a JSON object'
);

select lives_ok(
  $$
    insert into public.events (workspace_id, run_id, name)
    select workspace_a, run_in_a, 'comment_posted' from fixture
  $$,
  'an event can reference a run in its own workspace'
);
select throws_ok(
  $$
    insert into public.events (workspace_id, run_id, name)
    select workspace_a, run_in_b, 'comment_posted' from fixture
  $$,
  '23503',
  null,
  'an event cannot reference a run from another workspace'
);
select throws_ok(
  $$ delete from public.runs where id = (select run_in_a from fixture) $$,
  '23503',
  null,
  'a run that has events cannot be deleted'
);

select throws_ok(
  $$ update public.events set props = '{"edited": true}'::jsonb $$,
  'P0001',
  'events is append-only',
  'events cannot be updated'
);
select throws_ok(
  $$ delete from public.events $$,
  'P0001',
  'events is append-only',
  'events cannot be deleted'
);
select throws_ok(
  $$ truncate public.events $$,
  'P0001',
  'events is append-only',
  'events cannot be truncated'
);

set local role anon;
select is_empty($$ select id from public.events $$, 'anon cannot read events');
reset role;

set local role authenticated;
select is_empty($$ select id from public.events $$, 'authenticated users cannot read events');
reset role;

select * from finish();
rollback;
