begin;
create extension if not exists pgtap with schema extensions;

select plan(26);

create temp table fixture as
select
  gen_random_uuid() as workspace_a,
  gen_random_uuid() as user_a,
  encode(sha256('install-token-a'::bytea), 'hex') as token_hash_a;

insert into auth.users (id) select user_a from fixture;
insert into public.workspaces (id, name) select workspace_a, 'Workspace A' from fixture;

select has_table('public', 'cli_installs', 'cli_installs table exists');
select columns_are(
  'public', 'cli_installs',
  array['id', 'workspace_id', 'user_id', 'token_hash', 'created_at', 'revoked_at'],
  'cli_installs has exactly the expected columns'
);

select col_is_pk('public', 'cli_installs', 'id', 'id is the primary key');
select col_type_is('public', 'cli_installs', 'id', 'uuid', 'id is a uuid');
select col_has_default('public', 'cli_installs', 'id', 'id is generated by default');

select col_type_is('public', 'cli_installs', 'workspace_id', 'uuid', 'workspace_id is a uuid');
select col_not_null('public', 'cli_installs', 'workspace_id', 'workspace_id is required');
select fk_ok(
  'public', 'cli_installs', 'workspace_id', 'public', 'workspaces', 'id',
  'workspace_id references workspaces'
);
select col_is_unique(
  'public', 'cli_installs', array['workspace_id', 'id'],
  '(workspace_id, id) is unique so hook events can pin an install to its workspace'
);

select col_type_is('public', 'cli_installs', 'user_id', 'uuid', 'user_id is a uuid');
select col_not_null('public', 'cli_installs', 'user_id', 'every install token belongs to a user');
select fk_ok(
  'public', 'cli_installs', 'user_id', 'public', 'profiles', 'id',
  'user_id references profiles'
);

select col_type_is('public', 'cli_installs', 'token_hash', 'text', 'token_hash is text');
select col_not_null('public', 'cli_installs', 'token_hash', 'token_hash is required');
select col_is_unique('public', 'cli_installs', 'token_hash', 'token_hash is unique');

select col_type_is(
  'public', 'cli_installs', 'created_at', 'timestamp with time zone', 'created_at is a timestamptz'
);
select col_not_null('public', 'cli_installs', 'created_at', 'created_at is required');
select col_has_default('public', 'cli_installs', 'created_at', 'created_at is set by default');

select col_type_is(
  'public', 'cli_installs', 'revoked_at', 'timestamp with time zone', 'revoked_at is a timestamptz'
);
select col_is_null('public', 'cli_installs', 'revoked_at', 'an install is active until revoked');

select lives_ok(
  $$
    insert into public.cli_installs (workspace_id, user_id, token_hash)
    select workspace_a, user_a, token_hash_a from fixture
  $$,
  'an install is registered with a SHA-256 token hash'
);
select throws_ok(
  $$
    insert into public.cli_installs (workspace_id, user_id, token_hash)
    select workspace_a, user_a, token_hash_a from fixture
  $$,
  '23505',
  null,
  'two installs cannot share a token hash'
);
select throws_ok(
  $$
    insert into public.cli_installs (workspace_id, user_id, token_hash)
    select workspace_a, user_a, 'install-token-in-plain-text' from fixture
  $$,
  '23514',
  null,
  'a value that is not a lowercase SHA-256 hex digest is rejected, so raw tokens cannot be stored'
);
select throws_ok(
  $$ delete from auth.users where id = (select user_a from fixture) $$,
  '23503',
  null,
  'a user who still has installs cannot be deleted'
);

set local role anon;
select is_empty($$ select id from public.cli_installs $$, 'anon cannot read cli_installs');
reset role;

set local role authenticated;
select is_empty(
  $$ select id from public.cli_installs $$, 'authenticated users cannot read cli_installs'
);
reset role;

select * from finish();
rollback;
