begin;
create extension if not exists pgtap with schema extensions;

select plan(31);

create temp table fixture as
select
  gen_random_uuid() as workspace_a,
  gen_random_uuid() as workspace_b,
  gen_random_uuid() as user_a,
  gen_random_uuid() as install_in_a,
  gen_random_uuid() as install_in_b,
  gen_random_uuid() as run_in_a,
  gen_random_uuid() as run_in_b;

insert into auth.users (id) select user_a from fixture;

insert into public.workspaces (id, name)
select workspace_a, 'Workspace A' from fixture
union all
select workspace_b, 'Workspace B' from fixture;

insert into public.cli_installs (id, workspace_id, user_id, token_hash)
select install_in_a, workspace_a, user_a, encode(sha256('token-a'::bytea), 'hex') from fixture
union all
select install_in_b, workspace_b, user_a, encode(sha256('token-b'::bytea), 'hex') from fixture;

insert into public.runs (id, workspace_id, claude_session_id)
select run_in_a, workspace_a, 'session-a' from fixture
union all
select run_in_b, workspace_b, 'session-b' from fixture;

select has_table('public', 'hook_events', 'hook_events table exists');
select columns_are(
  'public', 'hook_events',
  array[
    'id', 'workspace_id', 'run_id', 'cli_install_id', 'hook_event_name', 'payload', 'received_at'
  ],
  'hook_events has exactly the expected columns'
);

select col_is_pk('public', 'hook_events', 'id', 'id is the primary key');
select col_type_is('public', 'hook_events', 'id', 'uuid', 'id is a uuid');
select col_has_default('public', 'hook_events', 'id', 'id is generated by default');

select col_type_is('public', 'hook_events', 'workspace_id', 'uuid', 'workspace_id is a uuid');
select col_not_null('public', 'hook_events', 'workspace_id', 'workspace_id is required');
select fk_ok(
  'public', 'hook_events', 'workspace_id', 'public', 'workspaces', 'id',
  'workspace_id references workspaces'
);

select col_type_is('public', 'hook_events', 'run_id', 'uuid', 'run_id is a uuid');
select col_not_null('public', 'hook_events', 'run_id', 'every hook event belongs to a run');
select fk_ok(
  'public', 'hook_events', array['workspace_id', 'run_id'],
  'public', 'runs', array['workspace_id', 'id'],
  '(workspace_id, run_id) references a run in the same workspace'
);

select col_type_is('public', 'hook_events', 'cli_install_id', 'uuid', 'cli_install_id is a uuid');
select col_not_null(
  'public', 'hook_events', 'cli_install_id', 'every hook event records the install that sent it'
);
select fk_ok(
  'public', 'hook_events', array['workspace_id', 'cli_install_id'],
  'public', 'cli_installs', array['workspace_id', 'id'],
  '(workspace_id, cli_install_id) references an install in the same workspace'
);

select col_type_is('public', 'hook_events', 'hook_event_name', 'text', 'hook_event_name is text');
select col_not_null('public', 'hook_events', 'hook_event_name', 'hook_event_name is required');

select col_type_is('public', 'hook_events', 'payload', 'jsonb', 'payload is jsonb');
select col_not_null('public', 'hook_events', 'payload', 'payload is required');

select col_type_is(
  'public', 'hook_events', 'received_at', 'timestamp with time zone', 'received_at is a timestamptz'
);
select col_not_null('public', 'hook_events', 'received_at', 'received_at is required');
select col_has_default('public', 'hook_events', 'received_at', 'received_at is set by default');

-- The five Claude Code hooks the MVP installer registers (AGENTS.md section 3).
select lives_ok(
  $$
    insert into public.hook_events (workspace_id, run_id, cli_install_id, hook_event_name, payload)
    select fixture.workspace_a, fixture.run_in_a, fixture.install_in_a, mvp_hook.name, '{}'::jsonb
    from fixture
    cross join unnest(
      array['SessionStart', 'UserPromptSubmit', 'PreToolUse', 'PostToolUse', 'Stop']
    ) as mvp_hook(name)
  $$,
  'every MVP hook event name is accepted'
);
select throws_ok(
  $$
    insert into public.hook_events (workspace_id, run_id, cli_install_id, hook_event_name, payload)
    select workspace_a, run_in_a, install_in_a, 'Notification', '{}'::jsonb from fixture
  $$,
  '23514',
  null,
  'a hook event name outside the MVP list is rejected'
);
select throws_ok(
  $$
    insert into public.hook_events (workspace_id, run_id, cli_install_id, hook_event_name, payload)
    select workspace_a, run_in_a, install_in_a, 'Stop', '["not", "an", "object"]'::jsonb
    from fixture
  $$,
  '23514',
  null,
  'payload must be a JSON object'
);
select throws_ok(
  $$
    insert into public.hook_events (workspace_id, run_id, cli_install_id, hook_event_name, payload)
    select workspace_a, run_in_b, install_in_a, 'Stop', '{}'::jsonb from fixture
  $$,
  '23503',
  null,
  'a hook event cannot reference a run from another workspace'
);
select throws_ok(
  $$
    insert into public.hook_events (workspace_id, run_id, cli_install_id, hook_event_name, payload)
    select workspace_a, run_in_a, install_in_b, 'Stop', '{}'::jsonb from fixture
  $$,
  '23503',
  null,
  'a hook event cannot reference an install from another workspace'
);

select throws_ok(
  $$ update public.hook_events set payload = '{"edited": true}'::jsonb $$,
  'P0001',
  'hook_events is append-only',
  'hook events cannot be updated'
);
select throws_ok(
  $$ delete from public.hook_events $$,
  'P0001',
  'hook_events is append-only',
  'hook events cannot be deleted'
);
select throws_ok(
  $$ truncate public.hook_events $$,
  'P0001',
  'hook_events is append-only',
  'hook events cannot be truncated'
);

set local role anon;
select is_empty($$ select id from public.hook_events $$, 'anon cannot read hook_events');
reset role;

set local role authenticated;
select is_empty(
  $$ select id from public.hook_events $$, 'authenticated users cannot read hook_events'
);
reset role;

select * from finish();
rollback;
